@echo off
echo Starting Chatbot UI Desktop App...
cd /d "%~dp0"
echo Checking Supabase status...
supabase status >nul 2>&1
if %errorlevel% neq 0 (
    echo Starting Supabase...
    supabase start
)
echo Starting desktop application...
npm run desktop
pause 